# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
latex: false
cache: 
  packages: yes
  directories:
    - $HOME/bin

install: echo "noop"
script:
- Rscript -e 'install.packages(c("tinytex", "withr"))'
- Rscript -e 'tinytex::install_tinytex()'
- Rscript -e 'system2("updmap-user")'
- Rscript -e 'dir.create("manuscript/dist")' 
- Rscript -e 'withr::with_dir("manuscript", tinytex::pdflatex("template.tex", pdf_file = "dist/manuscript.pdf"))'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: manuscript/dist